name: Build Resume

on:
  push:
    branches:
      - develop
    paths:
      - 'latex/resume.tex'
      - '.github/workflows/build_resume.yaml'

  workflow_dispatch:

jobs:
  build-PDF:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: docker-practice/actions-setup-docker@master

    - name: pwd
      run: echo $(pwd)

    - name: run-latex
      continue-on-error: true
      run: |
        docker run --rm \
        -v $(pwd)/latex:/app \
        -v $(pwd)/latex/font/Calibri:/usr/share/fonts/Calibri \
        -v $(pwd)/latex/font/fontspec:/usr/share/fonts/fontspec \
        -v $(pwd)/latex/font/Arial:/usr/share/fonts/Arial \
        blang/latex:ubuntu \
        sh -c "latexmk -pdf -f -xelatex -interaction=nonstopmode -synctex=1 -file-line-error -outdir=/app/output /app/resume.tex"
      
    - name: check-pdf-build
      run: |
        echo $(ls -R)
        FILE=latex/output/resume.pdf
        if test -f "$FILE"; 
        then
            echo "resume build success"
        else
          exit 1
        fi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: ./latex/output/resume.pdf
        retention-days: 30
    
    
