name: Build Resume

on:
  push:
    branches:
      - main
    paths:
      - 'latex/*'
      - '.github/workflows/build&release_resume.yml'

  workflow_dispatch:

jobs:
  build-PDF:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: docker-practice/actions-setup-docker@master

    - name: pwd
      run: echo $(pwd)

    - name: run-latex
      continue-on-error: true
      run: |
        docker run --rm \
        -v $(pwd)/latex:/app \
        -v $(pwd)/latex/font/Calibri:/usr/share/fonts/Calibri \
        -v $(pwd)/latex/font/fontspec:/usr/share/fonts/fontspec \
        -v $(pwd)/latex/font/Arial:/usr/share/fonts/Arial \
        blang/latex:ubuntu \
        sh -c "latexmk -pdf -f -xelatex -interaction=nonstopmode -synctex=1 -file-line-error -outdir=/app/output /app/resume.tex"
      
    - name: check-pdf-build
      run: |
        echo $(ls -R)
        FILE=latex/output/resume.pdf
        if test -f "$FILE"; 
        then
            echo "resume build success"
        else
          exit 1
        fi
    
    - name: Create Release
      id: create_release
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    